import Foundation

// MARK: - Insight

/// An actionable insight generated by the PatternEngine.
/// May surface as a notification, in the Insights tab, or both.
struct Insight: Codable, Identifiable {
    let id: String
    let type: InsightType
    let title: String
    let body: String
    let priority: InsightPriority
    let category: String
    let relatedEventIds: [String]
    let createdAt: Date
    let expiresAt: Date?

    init(
        type: InsightType,
        title: String,
        body: String,
        priority: InsightPriority,
        category: String = "",
        relatedEventIds: [String] = [],
        expiresAt: Date? = nil
    ) {
        self.id = UUID().uuidString
        self.type = type
        self.title = title
        self.body = body
        self.priority = priority
        self.category = category
        self.relatedEventIds = relatedEventIds
        self.createdAt = Date()
        self.expiresAt = expiresAt
    }

    /// Whether this insight is still valid (hasn't expired).
    var isActive: Bool {
        if let expires = expiresAt {
            return Date() < expires
        }
        return true
    }
}

// MARK: - Insight Type

enum InsightType: String, Codable {
    case spendingTrend          // "You spent 30% more on dining this week"
    case anomaly                // "Unusual $500 charge at..."
    case locationCorrelation    // "You spent $45 at the restaurant you visited"
    case healthPattern          // "You've worked out 4 days in a row!"
    case routine                // "You typically leave for work at 8:15am"
    case ghostSubscription      // Recurring forgotten charge
    case milestone              // "You've saved $200 vs last month"
    case categorySpike          // "Electronics spending is 3x your average"
    case eatingPattern          // "You eat out 4x/week, mostly on Fridays"
    case screenTimeAlert        // "3 hours on social media today"
    case vitaminD               // "Only 15 min of outdoor time today"
    case foodPattern            // "You eat chicken biryani 3x/week"
    case nutritionAlert         // "No vegetables logged in 3 days"
    case foodSpending           // "Food delivery is 40% of your spending"
    case mealStreak             // "Cooked at home 5 days straight!"

    var icon: String {
        switch self {
        case .spendingTrend: return "chart.line.uptrend.xyaxis"
        case .anomaly: return "exclamationmark.triangle.fill"
        case .locationCorrelation: return "mappin.and.ellipse"
        case .healthPattern: return "figure.run"
        case .routine: return "clock.fill"
        case .ghostSubscription: return "ghost"
        case .milestone: return "star.fill"
        case .categorySpike: return "chart.bar.fill"
        case .eatingPattern: return "fork.knife"
        case .screenTimeAlert: return "iphone"
        case .vitaminD: return "sun.max.fill"
        case .foodPattern: return "fork.knife.circle.fill"
        case .nutritionAlert: return "leaf.fill"
        case .foodSpending: return "cart.fill"
        case .mealStreak: return "flame.fill"
        }
    }
}

// MARK: - Insight Priority

enum InsightPriority: Int, Codable, Comparable {
    case low = 0        // In-app only, never a notification
    case medium = 1     // Notification if budget allows
    case high = 2       // Notification unless recently notified same type
    case urgent = 3     // Always notify (anomaly, unusual charge)

    static func < (lhs: InsightPriority, rhs: InsightPriority) -> Bool {
        lhs.rawValue < rhs.rawValue
    }

    var label: String {
        switch self {
        case .low: return "Info"
        case .medium: return "Notable"
        case .high: return "Important"
        case .urgent: return "Urgent"
        }
    }
}
